
name: C Build and Run

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get install -y build-essential

      # Compile the code

      - name: Compile the Code
        run: gcc Temperature_Converter.c -o TC

      # Run Values

      - name: Run Values
        run: |
          cat <<EOF >Input.txt
          A
          1
          27
          Y
          A
          2
          300
          Y
          B
          1
          101
          Y
          B
          2
          39
          Y
          C
          1
          200
          Y
          C
          2
          101
          N
          EOF

      # Run the code

      - name: Run the code
        run: |
          echo -e "Test Run Result:\n" > Test-Run-Result/Result.txt
          ./TC < Input.txt >> Test-Run-Result/Result.txt

      # Push Result to Repo

      - name: Upload Temperature Converter Test Run Results to Repo
        uses: actions/upload-artifact@v4
        with:
          name: Push Temperature Converter Test-Run-Result
          path: Test-Run-Result/Result.txt
      - name: Push Result.txt to Repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add Test-Run-Result/Result.txt
          git commit -m "Update Temperature Converter output [skip ci]" || echo "No changes to commit"
          git push
